<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputAddress</name>
   <tag></tag>
   <elementGuidId>03e52c0d-fc64-49aa-adc0-1e5a4f4452f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billing_address_1' and @id = 'billing_address_1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc4374aa-130a-4155-b803-f6fbd9fff87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address_1</value>
      <webElementGuid>6e7632f1-96ab-401d-9d57-d4442affc805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_address_1</value>
      <webElementGuid>83fbafe5-48f1-4856-ac75-1d7795ee9569</webElementGuid>
   </webElementProperties>
</WebElementEntity>
